#!/usr/bin/env ruby

require 'rubygems'
begin
  require 'gitstagram'
rescue LoadError
  STDERR.puts 'Gistagram is not install. Run: gem install gitstagram'
end

begin
  Gitstagram::Snapshot.smile
rescue Exception => e
  STDERR.puts e.message
  STDERR.puts e.backtrace.join(', ')
end
exit 0